adjust docker to get types
meteorMoon/POCBack pull request #16
Opened 2022-08-22 20:58 UTC by daryo918

get user id from jwt with a middleware

2022-08-22 21:12 UTC, Nicolas000 approved these changes

2022-08-27 18:43 UTC, esteban027 commented on app/@types/express/index.d.ts
> +console.log("Starting");
Do we still need this console Log ?

2022-08-27 18:43 UTC, esteban027 commented on app/src/controllers/index.controller.ts
> +  console.log(req.userId)
Same as last comment, do we need this log ?

2022-09-11 17:07 UTC, esteban027 requested changes
Remove console logs

2022-09-16 19:10 UTC, closed without merging