Features/buyproduct
meteorMoon/POCBack pull request #17
Opened 2022-09-08 02:17 UTC by daryo918

cart functionality

2022-09-08 02:19 UTC, Nicolas000 approved these changes

2022-09-11 17:04 UTC, esteban027 commented
Please Cahnge the objective branch to develop

2022-09-11 17:06 UTC, esteban027 requested changes

2022-09-11 17:06 UTC, esteban027 commented on app/src/controllers/products.controllers.ts
> +    message: "mostrar productos"
Only english

2022-09-11 17:06 UTC, esteban027 commented on app/src/controllers/products.controllers.ts
> +        message: "quitar x producto"
only english please

2022-09-11 17:06 UTC, esteban027 commented on app/src/controllers/products.controllers.ts
> +        message: "validar pago"
Only english please

2022-09-11 17:06 UTC, esteban027 commented on postgres/users.sql
> +create table producto(
only english please

2022-09-11 17:06 UTC, esteban027 commented on postgres/users.sql
> +create table details(
only english please

2022-09-11 17:06 UTC, esteban027 commented on postgres/users.sql
> +insert into producto(nombre,precio,stock) values ('Coca-cola',1000,1000);
same comment as before

2022-09-16 19:09 UTC, closed without merging