jwt y login
meteorMoon/POCBack pull request #4
Opened 2022-06-17 00:07 UTC by daryo918

2022-06-17 00:31 UTC, Nicolas000 approved these changes

2022-06-17 01:33 UTC, esteban027 commented on app/src/controllers/index.controller.ts
> +
Please leave only 1 space before the function.

2022-06-17 01:34 UTC, esteban027 requested changes

2022-06-17 01:34 UTC, esteban027 commented on app/src/controllers/index.controller.ts
> +
please leave only 1 space before

2022-06-17 01:34 UTC, esteban027 commented on app/src/index.ts
> +
Leave only 1 space.

2022-06-17 01:34 UTC, esteban027 commented on app/src/libs/validateToken.ts
> +
please leave only 1 space.

2022-06-18 01:57 UTC, esteban027 approved these changes

2022-06-18 01:59 UTC, merged